services:
  - type: web
    name: prelaunch-fastapi
    env: python
    buildCommand: |
      pip install -r backend/requirements.txt
    startCommand: |
      uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    plan: free
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        value: sqlite:///./prelaunch.db
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: SHARED_SECRET
        sync: false
    rootDir: backend

  - type: worker
    name: prelaunch-discord-bot
    env: python
    buildCommand: |
      pip install -r bot/requirements.txt
    startCommand: |
      python bot.py
    plan: free
    autoDeploy: true
    envVars:
      - key: API_BASE
        sync: false
      - key: SHARED_SECRET
        sync: false
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: GUILD_ID
        value: ""
    rootDir: bot
